language: minimal
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - cd udagram-api-feed && docker build -t udagram-feed .
  - docker tag udagram-feed:latest dockeralcoder/feedapi:latest && cd ..
  - cd udagram-api-users:latest && docker build -t udagram-users .
  - docker tag udagram-users:latest dockeralcoder/usersapi:latest && cd ..
  - cd udagram-frontend:latest && docker build -t udagram-frontend .
  - docker tag udagram-frontend:latest dockeralcoder/frontendapi:latest && cd ..

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dockeralcoder/feedapi:latest
  - docker push dockeralcoder/usersapi:latest
  - docker push dockeralcoder/frontendapi:latest