apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-users
  template:
    metadata:
      labels:
        app: udagram-users
    spec:
      containers:
      - name: usersapi
        image: dockeralcoder/usersapi:latest
        ports:
        - containerPort: 8100