version: "3"
services:
 reverseproxy:
   image: dockeralcoder/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - usersapi
    - feedapi   
 backend-user:
  image: dockeralcoder/usersapi
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_DATABASE: $POSTGRESS_DATABASE
   POSTGRESS_HOST: $POSTGRESS_HOST
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 backend-feed:
  image: dockeralcoder/feedapi
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRESS_DATABASE: $POSTGRESS_DATABASE
   POSTGRESS_HOST: $POSTGRESS_HOST
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 frontend:
  image: dockeralcoder/frontendapi
  ports:
   - "8100:80"